# -*- mode: python ; coding: utf-8 -*-

a = Analysis(['main.py'],
             pathex=[],
             binaries=[],
             datas=[("./icon", "icon"), ("./Putty", "Putty"), ("./utils", "utils"),
                    ("./ui", "ui"), ("./window", "window"), ("./PuttyTools.reg", "Theme"),
                    ("./README.md", "README")],
             hiddenimports=["Crypto.Cipher.AES", "Crypto.Util.Padding","Crypto.Random",
                            "sqlite3", "qdarkstyle", "PyQt5.QtSql", "subprocess"],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(pyz,
          a.scripts, 
          [],
          exclude_binaries=True,
          name='PuttyTools',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None,
          windowed=True,
          contents_directory='.',
          version='verison_info.txt')
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas, 
               strip=False,
               name="PuttyTools",
               upx=True,
               upx_exclude=[])
