# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PuttyTools(object):
    def setupUi(self, PuttyTools):
        PuttyTools.setObjectName("PuttyTools")
        PuttyTools.resize(500, 400)
        PuttyTools.setMinimumSize(QtCore.QSize(500, 400))
        PuttyTools.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(PuttyTools)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scpBox = QtWidgets.QGroupBox(self.centralwidget)
        self.scpBox.setEnabled(False)
        self.scpBox.setFlat(False)
        self.scpBox.setCheckable(False)
        self.scpBox.setObjectName("scpBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scpBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.scpBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.scpBox)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 3, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.scpBox)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 2, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.scpBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scpBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.scpBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scpBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 2)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 5)
        self.gridLayout_2.setColumnStretch(2, 3)
        self.gridLayout_2.setColumnStretch(3, 1)
        self.gridLayout_3.addWidget(self.scpBox, 1, 1, 1, 1)
        self.fileInfoBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.fileInfoBox.setFont(font)
        self.fileInfoBox.setMouseTracking(True)
        self.fileInfoBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fileInfoBox.setAutoFillBackground(False)
        self.fileInfoBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.fileInfoBox.setFlat(False)
        self.fileInfoBox.setCheckable(False)
        self.fileInfoBox.setChecked(False)
        self.fileInfoBox.setObjectName("fileInfoBox")
        self.gridLayout = QtWidgets.QGridLayout(self.fileInfoBox)
        self.gridLayout.setObjectName("gridLayout")
        self.pwd_lab = QtWidgets.QLabel(self.fileInfoBox)
        self.pwd_lab.setObjectName("pwd_lab")
        self.gridLayout.addWidget(self.pwd_lab, 3, 0, 1, 1)
        self.pwd_edit = QtWidgets.QLineEdit(self.fileInfoBox)
        self.pwd_edit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pwd_edit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pwd_edit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.pwd_edit.setCursorPosition(0)
        self.pwd_edit.setReadOnly(True)
        self.pwd_edit.setPlaceholderText("")
        self.pwd_edit.setObjectName("pwd_edit")
        self.gridLayout.addWidget(self.pwd_edit, 3, 1, 1, 1)
        self.port_lab = QtWidgets.QLabel(self.fileInfoBox)
        self.port_lab.setObjectName("port_lab")
        self.gridLayout.addWidget(self.port_lab, 1, 0, 1, 1)
        self.port_edit = QtWidgets.QLineEdit(self.fileInfoBox)
        self.port_edit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.port_edit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.port_edit.setText("")
        self.port_edit.setMaxLength(5)
        self.port_edit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.port_edit.setCursorPosition(0)
        self.port_edit.setReadOnly(True)
        self.port_edit.setPlaceholderText("")
        self.port_edit.setObjectName("port_edit")
        self.gridLayout.addWidget(self.port_edit, 1, 1, 1, 1)
        self.username_lab = QtWidgets.QLabel(self.fileInfoBox)
        self.username_lab.setObjectName("username_lab")
        self.gridLayout.addWidget(self.username_lab, 2, 0, 1, 1)
        self.host_lab = QtWidgets.QLabel(self.fileInfoBox)
        self.host_lab.setObjectName("host_lab")
        self.gridLayout.addWidget(self.host_lab, 0, 0, 1, 1)
        self.username_edit = QtWidgets.QLineEdit(self.fileInfoBox)
        self.username_edit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.username_edit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.username_edit.setCursorPosition(0)
        self.username_edit.setReadOnly(True)
        self.username_edit.setPlaceholderText("")
        self.username_edit.setObjectName("username_edit")
        self.gridLayout.addWidget(self.username_edit, 2, 1, 1, 1)
        self.host_edit = QtWidgets.QLineEdit(self.fileInfoBox)
        self.host_edit.setTabletTracking(False)
        self.host_edit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.host_edit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.host_edit.setInputMask("")
        self.host_edit.setCursorPosition(0)
        self.host_edit.setReadOnly(True)
        self.host_edit.setPlaceholderText("")
        self.host_edit.setObjectName("host_edit")
        self.gridLayout.addWidget(self.host_edit, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 7)
        self.gridLayout_3.addWidget(self.fileInfoBox, 0, 1, 1, 1)
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.treeView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeView.setIconSize(QtCore.QSize(20, 20))
        self.treeView.setItemsExpandable(True)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setCascadingSectionResizes(True)
        self.gridLayout_3.addWidget(self.treeView, 0, 0, 3, 1)
        self.showMsg = QtWidgets.QTextBrowser(self.centralwidget)
        self.showMsg.setMouseTracking(False)
        self.showMsg.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.showMsg.setObjectName("showMsg")
        self.gridLayout_3.addWidget(self.showMsg, 2, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 4)
        self.gridLayout_3.setColumnStretch(1, 6)
        self.gridLayout_3.setRowStretch(0, 4)
        self.gridLayout_3.setRowStretch(1, 3)
        self.gridLayout_3.setRowStretch(2, 3)
        PuttyTools.setCentralWidget(self.centralwidget)
        self.actionAddFile = QtWidgets.QAction(PuttyTools)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/tianjiawenjian.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddFile.setIcon(icon)
        self.actionAddFile.setObjectName("actionAddFile")
        self.actionDelFile = QtWidgets.QAction(PuttyTools)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/shanchuwenjian.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelFile.setIcon(icon1)
        self.actionDelFile.setObjectName("actionDelFile")
        self.actionAddFolder = QtWidgets.QAction(PuttyTools)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/xinzengwenjianjia.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddFolder.setIcon(icon2)
        self.actionAddFolder.setObjectName("actionAddFolder")
        self.actionDelFolder = QtWidgets.QAction(PuttyTools)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/shanchuwenjianjia.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelFolder.setIcon(icon3)
        self.actionDelFolder.setObjectName("actionDelFolder")
        self.actionRenameFolder = QtWidgets.QAction(PuttyTools)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/bianjiwenjianjia.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRenameFolder.setIcon(icon4)
        self.actionRenameFolder.setObjectName("actionRenameFolder")
        self.actionRenameFile = QtWidgets.QAction(PuttyTools)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/bianjiwenjian.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRenameFile.setIcon(icon5)
        self.actionRenameFile.setObjectName("actionRenameFile")

        self.retranslateUi(PuttyTools)
        self.treeView.customContextMenuRequested['QPoint'].connect(PuttyTools.showMenu)
        self.treeView.clicked['QModelIndex'].connect(PuttyTools.treeOneClick)
        self.host_edit.selectionChanged.connect(PuttyTools.selected_text)
        self.port_edit.selectionChanged.connect(PuttyTools.selected_text)
        self.username_edit.selectionChanged.connect(PuttyTools.selected_text)
        self.pwd_edit.selectionChanged.connect(PuttyTools.selected_text)
        QtCore.QMetaObject.connectSlotsByName(PuttyTools)
        PuttyTools.setTabOrder(self.treeView, self.host_edit)
        PuttyTools.setTabOrder(self.host_edit, self.port_edit)
        PuttyTools.setTabOrder(self.port_edit, self.username_edit)
        PuttyTools.setTabOrder(self.username_edit, self.pwd_edit)
        PuttyTools.setTabOrder(self.pwd_edit, self.lineEdit)
        PuttyTools.setTabOrder(self.lineEdit, self.pushButton_2)
        PuttyTools.setTabOrder(self.pushButton_2, self.lineEdit_2)
        PuttyTools.setTabOrder(self.lineEdit_2, self.checkBox)
        PuttyTools.setTabOrder(self.checkBox, self.pushButton)

    def retranslateUi(self, PuttyTools):
        _translate = QtCore.QCoreApplication.translate
        PuttyTools.setWindowTitle(_translate("PuttyTools", "PuttyTools V2.1"))
        self.scpBox.setTitle(_translate("PuttyTools", "复制文件"))
        self.label.setText(_translate("PuttyTools", "本地:"))
        self.pushButton_2.setText(_translate("PuttyTools", "选择路径"))
        self.checkBox.setText(_translate("PuttyTools", "复制文件到本地"))
        self.pushButton.setText(_translate("PuttyTools", "开始"))
        self.label_2.setText(_translate("PuttyTools", "远程:"))
        self.fileInfoBox.setTitle(_translate("PuttyTools", "文件信息"))
        self.pwd_lab.setText(_translate("PuttyTools", "passWord:"))
        self.port_lab.setText(_translate("PuttyTools", "port:"))
        self.username_lab.setText(_translate("PuttyTools", "userName:"))
        self.host_lab.setText(_translate("PuttyTools", "host:"))
        self.actionAddFile.setText(_translate("PuttyTools", "新建文件"))
        self.actionAddFile.setToolTip(_translate("PuttyTools", "新建文件"))
        self.actionDelFile.setText(_translate("PuttyTools", "删除文件"))
        self.actionDelFile.setToolTip(_translate("PuttyTools", "删除文件"))
        self.actionAddFolder.setText(_translate("PuttyTools", "新建文件夹"))
        self.actionAddFolder.setToolTip(_translate("PuttyTools", "新建文件夹"))
        self.actionDelFolder.setText(_translate("PuttyTools", "删除文件夹"))
        self.actionDelFolder.setToolTip(_translate("PuttyTools", "删除文件夹"))
        self.actionRenameFolder.setText(_translate("PuttyTools", "重命名文件夹"))
        self.actionRenameFolder.setToolTip(_translate("PuttyTools", "重命名"))
        self.actionRenameFile.setText(_translate("PuttyTools", "修改文件"))
        self.actionRenameFile.setToolTip(_translate("PuttyTools", "修改文件"))
from icon import apprcc_rc
